[package]
name = "init"
version = "0.0.1"
edition = "2021"
authors = ["Emanuel"]
description = "PID 1 init system to Igloo."

[dependencies]
libc = "0.2"

[profile.release]
opt-level = "z"     
lto = true          
strip = true        
panic = "abort"     
codegen-units = 1