[package]
name = "install"
version = "0.1.0"
edition = "2021"

[dependencies]
dialoguer = "0.11"
regex = "1"
nix = { version = "0.31.1", features = ["fs", "user", "hostname", "process"] }
tempfile = "3"